apiVersion: lifecycle.suse.com/v1alpha1
kind: ReleaseManifest
metadata:
  name: release-manifest-3-2-0
spec:
  releaseVersion: 3.2.0
  components:
    kubernetes:
      k3s:
        version: v1.31.3+k3s1
        coreComponents:
          - name: traefik-crd
            version: 27.0.201+up27.0.2
            type: HelmChart
          - name: traefik
            version: 27.0.201+up27.0.2
            type: HelmChart
          - name: local-path-provisioner
            containers:
              - name: local-path-provisioner
                image: rancher/local-path-provisioner:v0.0.30
            type: Deployment
          - name: coredns
            containers:
              - name: coredns
                image: rancher/mirrored-coredns-coredns:1.11.3
            type: Deployment
          - name: metrics-server
            containers:
              - name: metrics-server
                image: rancher/mirrored-metrics-server:v0.7.2
            type: Deployment
      rke2:
        version: v1.31.3+rke2r1
        coreComponents:
          - name: rke2-cilium
            version: 1.16.303
            type: HelmChart
          - name: rke2-canal
            version: v3.29.0-build2024110400
            type: HelmChart
          - name: rke2-calico-crd
            version: v3.29.000
            type: HelmChart
          - name: rke2-calico
            version: v3.29.000
            type: HelmChart
          - name: rke2-coredns
            version: 1.33.005
            type: HelmChart
          - name: rke2-ingress-nginx
            version: 4.10.502
            type: HelmChart
          - name: rke2-metrics-server
            version: 3.12.004
            type: HelmChart
          - name: rancher-vsphere-csi
            version: 3.3.1-rancher700
            type: HelmChart
          - name: rancher-vsphere-cpi
            version: 1.9.100
            type: HelmChart
          - name: harvester-cloud-provider
            version: 0.2.600
            type: HelmChart
          - name: harvester-csi-driver
            version: 0.1.2000
            type: HelmChart
          - name: rke2-snapshot-controller-crd
            version: 3.0.601
            type: HelmChart
          - name: rke2-snapshot-controller
            version: 3.0.601
            type: HelmChart
          - name: rke2-snapshot-validation-webhook
            version: 1.9.001
            type: HelmChart
    operatingSystem:
      version: "6.0"
      zypperID: "SL-Micro"
      cpeScheme: "cpe:/o:suse:sl-micro:6.0"
      prettyName: "SUSE Linux Micro 6.0"
      supportedArchs:
        - "x86_64"
        - "aarch64"
    workloads:
      helm:
        - prettyName: Rancher
          releaseName: rancher
          chart: rancher
          version: 2.10.1
          repository: https://charts.rancher.com/server-charts/prime
          values:
            postDelete:
              enabled: false
        - prettyName: Longhorn
          releaseName: longhorn
          chart: longhorn
          version: 105.1.0+up1.7.2
          repository: https://charts.rancher.io
          dependencyCharts:
            - releaseName: longhorn-crd
              chart: longhorn-crd
              version: 105.1.0+up1.7.2
              repository: https://charts.rancher.io
        - prettyName: MetalLB
          releaseName: metallb
          chart: oci://registry.suse.com/edge/3.2/metallb-chart
          version: 302.0.0+up0.14.9
        - prettyName: CDI
          releaseName: cdi
          chart: oci://registry.suse.com/edge/3.2/cdi-chart
          version: 302.0.0+up0.4.0
        - prettyName: KubeVirt
          releaseName: kubevirt
          chart: oci://registry.suse.com/edge/3.2/kubevirt-chart
          version: 302.0.0+up0.4.0
          addonCharts:
            - releaseName: kubevirt-dashboard-extension
              chart: oci://registry.suse.com/edge/3.2/kubevirt-dashboard-extension-chart
              version: 302.0.0+up1.2.1
        - prettyName: NeuVector
          releaseName: neuvector
          chart: neuvector
          version: 105.0.0+up2.8.3
          repository: https://charts.rancher.io
          dependencyCharts:
            - releaseName: neuvector-crd
              chart: neuvector-crd
              version: 105.0.0+up2.8.3
              repository: https://charts.rancher.io
          addonCharts:
            - releaseName: neuvector-ui-ext
              chart: neuvector-ui-ext
              repository: https://github.com/rancher/ui-plugin-charts/raw/main
              version: 2.0.1
        - prettyName: EndpointCopierOperator
          releaseName: endpoint-copier-operator
          chart: oci://registry.suse.com/edge/3.2/endpoint-copier-operator-chart
          version: 302.0.0+up0.2.1
        - prettyName: Elemental
          releaseName: elemental-operator
          chart: oci://registry.suse.com/rancher/elemental-operator-chart
          version: 1.6.5
          dependencyCharts:
            - releaseName: elemental-operator-crds
              chart: oci://registry.suse.com/rancher/elemental-operator-crds-chart
              version: 1.6.5
          addonCharts:
            - releaseName: elemental
              chart: elemental
              repository: https://github.com/rancher/ui-plugin-charts/raw/main
              version: 3.0.0
        - prettyName: SRIOV
          releaseName: sriov-network-operator
          chart: oci://registry.suse.com/edge/3.2/sriov-network-operator-chart
          version: 302.0.0+up1.4.0
          dependencyCharts:
            - releaseName: sriov-crd
              chart: oci://registry.suse.com/edge/3.2/sriov-crd-chart
              version: 302.0.0+up1.4.0
        - prettyName: Akri
          releaseName: akri
          chart: oci://registry.suse.com/edge/3.2/akri-chart
          version: 302.0.0+up0.12.20
          addonCharts:
            - releaseName: akri-dashboard-extension
              chart: oci://registry.suse.com/edge/3.2/akri-dashboard-extension-chart
              version: 302.0.0+up1.2.1
        - prettyName: Metal3
          releaseName: metal3
          chart: oci://registry.suse.com/edge/3.2/metal3-chart
          version: 302.0.0+up0.9.0
        - prettyName: RancherTurtles
          releaseName: rancher-turtles
          chart: oci://registry.suse.com/edge/3.2/rancher-turtles-chart
          version: 302.0.0+up0.14.1