apiVersion: lifecycle.suse.com/v1alpha1
kind: ReleaseManifest
metadata:
  name: release-manifest-3-3-1
spec:
  releaseVersion: 3.3.1
  components:
    kubernetes:
      k3s:
        version: v1.32.4+k3s1
        coreComponents:
          - name: traefik-crd
            version: 34.2.1+up34.2.0
            type: HelmChart
          - name: traefik
            version: 34.2.1+up34.2.0
            type: HelmChart
          - name: local-path-provisioner
            containers:
              - name: local-path-provisioner
                image: rancher/local-path-provisioner:v0.0.31
            type: Deployment
          - name: coredns
            containers:
              - name: coredns
                image: rancher/mirrored-coredns-coredns:1.12.1
            type: Deployment
          - name: metrics-server
            containers:
              - name: metrics-server
                image: rancher/mirrored-metrics-server:v0.7.2
            type: Deployment
      rke2:
        version: v1.32.4+rke2r1
        coreComponents:
          - name: rke2-cilium
            version: 1.17.300
            type: HelmChart
          - name: rke2-canal
            version: v3.29.3-build2025040801
            type: HelmChart
          - name: rke2-calico-crd
            version: v3.29.101
            type: HelmChart
          - name: rke2-calico
            version: v3.29.300
            type: HelmChart
          - name: rke2-coredns
            version: 1.39.201
            type: HelmChart
          - name: rke2-ingress-nginx
            version: 4.12.101
            type: HelmChart
          - name: rke2-metrics-server
            version: 3.12.200
            type: HelmChart
          - name: rancher-vsphere-csi
            version: 3.3.1-rancher900
            type: HelmChart
          - name: rancher-vsphere-cpi
            version: 1.10.000
            type: HelmChart
          - name: harvester-cloud-provider
            version: 0.2.900
            type: HelmChart
          - name: harvester-csi-driver
            version: 0.1.2300
            type: HelmChart
          - name: rke2-snapshot-controller-crd
            version: 4.0.002
            type: HelmChart
          - name: rke2-snapshot-controller
            version: 4.0.002
            type: HelmChart
          # Deprecated this empty chart addon can be removed in v1.34
          - name: rke2-snapshot-validation-webhook
            version: 0.0.0
            type: HelmChart
    operatingSystem:
      version: "6.1"
      zypperID: "SL-Micro"
      cpeScheme: "cpe:/o:suse:sl-micro:6.1"
      prettyName: "SUSE Linux Micro 6.1"
      supportedArchs:
        - "x86_64"
        - "aarch64"
    workloads:
      helm:
        - prettyName: Rancher
          releaseName: rancher
          chart: rancher
          version: 2.11.2
          repository: https://charts.rancher.com/server-charts/prime
          values:
            postDelete:
              enabled: false
        - prettyName: Longhorn
          releaseName: longhorn
          chart: longhorn
          version: 106.2.0+up1.8.1
          repository: https://charts.rancher.io
          dependencyCharts:
            - releaseName: longhorn-crd
              chart: longhorn-crd
              version: 106.2.0+up1.8.1
              repository: https://charts.rancher.io
        - prettyName: MetalLB
          releaseName: metallb
          chart: "oci://registry.suse.com/edge/charts/metallb"
          version: "303.0.0+up0.14.9"
        - prettyName: CDI
          releaseName: cdi
          chart: "oci://registry.suse.com/edge/charts/cdi"
          version: "303.0.0+up0.5.0"
        - prettyName: KubeVirt
          releaseName: kubevirt
          chart: "oci://registry.suse.com/edge/charts/kubevirt"
          version: "303.0.0+up0.5.0"
          addonCharts:
            - releaseName: kubevirt-dashboard-extension
              chart: "oci://registry.suse.com/edge/charts/kubevirt-dashboard-extension"
              version: "303.0.2+up1.3.2"
        - prettyName: NeuVector
          releaseName: neuvector
          chart: neuvector
          version: 106.0.1+up2.8.6
          repository: https://charts.rancher.io
          dependencyCharts:
            - releaseName: neuvector-crd
              chart: neuvector-crd
              version: 106.0.1+up2.8.6
              repository: https://charts.rancher.io
          addonCharts:
            - releaseName: neuvector-ui-ext
              chart: neuvector-ui-ext
              repository: https://github.com/rancher/ui-plugin-charts/raw/main
              version: 2.1.3
        - prettyName: EndpointCopierOperator
          releaseName: endpoint-copier-operator
          chart: "oci://registry.suse.com/edge/charts/endpoint-copier-operator"
          version: "303.0.0+up0.2.1"
        - prettyName: Elemental
          releaseName: elemental-operator
          chart: oci://registry.suse.com/rancher/elemental-operator-chart
          version: 1.6.8
          dependencyCharts:
            - releaseName: elemental-operator-crds
              chart: oci://registry.suse.com/rancher/elemental-operator-crds-chart
              version: 1.6.8
          addonCharts:
            - releaseName: elemental
              chart: elemental
              repository: https://github.com/rancher/ui-plugin-charts/raw/main
              version: 3.0.0
        - prettyName: SRIOV
          releaseName: sriov-network-operator
          chart: "oci://registry.suse.com/edge/charts/sriov-network-operator"
          version: "303.0.2+up1.5.0"
          dependencyCharts:
            - releaseName: sriov-crd
              chart: "oci://registry.suse.com/edge/charts/sriov-crd"
              version: "303.0.2+up1.5.0"
        - prettyName: Akri
          releaseName: akri
          chart: "oci://registry.suse.com/edge/charts/akri"
          version: "303.0.0+up0.12.20"
          addonCharts:
            - releaseName: akri-dashboard-extension
              chart: "oci://registry.suse.com/edge/charts/akri-dashboard-extension"
              version: "303.0.2+up1.3.1"
        - prettyName: Metal3
          releaseName: metal3
          chart: "oci://registry.suse.com/edge/charts/metal3"
          version: "303.0.7+up0.11.5"
        - prettyName: RancherTurtles
          releaseName: rancher-turtles
          chart: "oci://registry.suse.com/edge/charts/rancher-turtles"
          version: "303.0.4+up0.20.0"